# Generated by Django 6.0.2 on 2026-02-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='authority_type',
            field=models.CharField(choices=[('ndrf', 'NDRF'), ('police', 'Police'), ('fire', 'Fire Department'), ('medical', 'Medical Emergency'), ('sdrf', 'SDRF')], max_length=20),
        ),
    ]
