# Generated by Django 6.0.2 on 2026-02-27 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disasters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_radius_km', models.IntegerField(default=5)),
                ('min_severity', models.IntegerField(default=5)),
                ('disaster_types', models.JSONField(default=list, help_text='List of disaster types to alert for')),
                ('alert_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Locations',
            },
        ),
        migrations.CreateModel(
            name='DisasterAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_sent_at', models.DateTimeField(auto_now_add=True)),
                ('alert_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], default='sent', max_length=20)),
                ('distance_km', models.FloatField()),
                ('evacuation_route', models.JSONField(blank=True, null=True)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alerts', to='disasters.disaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaster_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-alert_sent_at'],
                'unique_together': {('user', 'disaster')},
            },
        ),
        migrations.CreateModel(
            name='EvacuationZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.IntegerField()),
                ('radius_km_from', models.FloatField()),
                ('radius_km_to', models.FloatField()),
                ('evacuation_order_issued_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_users_affected', models.IntegerField(default=0)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_zones', to='disasters.disaster')),
            ],
            options={
                'ordering': ['disaster', 'zone_number'],
                'unique_together': {('disaster', 'zone_number')},
            },
        ),
    ]
